# -*- mode: ruby -*-
# vi: set ft=ruby :

load '../common/nemea-dashboard.rb'

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 2280
  config.vm.network "forwarded_port", guest: 5555, host: 5555

  config.vm.provision "shell", inline: <<-SHELL
     sudo rpm -ivh https://homeproj.cesnet.cz/rpm/liberouter/devel/x86_64/liberouter-devel-1.0.0-1.noarch.rpm
     sudo yum install -y wget
     sudo wget -O /etc/yum.repos.d/cesnet-nemea.repo https://copr.fedorainfracloud.org/coprs/g/CESNET/NEMEA/repo/epel-7/group_CESNET-NEMEA-epel-7.repo
     sudo rpm --import https://copr-be.cloud.fedoraproject.org/results/@CESNET/NEMEA/pubkey.gpg
     sudo yum install -y nemea nemea-cesnet-modules ipfixcol ipfixcol-unirec-output
SHELL
   config.vm.provision "shell", inline: $nemeadashboard
end
