name: C/C++ CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git build-essential autoconf libtool libpcap-dev pkg-config libxml2-dev gawk libcurl4-openssl-dev libxml2-dev libyaml-dev make python3 python3-dev python3-pip python3-setuptools libxml2-dev libxml2 libpcap0.8-dev libpcap0.8 libidn2-0-dev
        ( cd /tmp; wget -qO - http://libnf.net/packages/libnf-1.25.tar.gz | tar -xzf - && cd libnf-1.25 && ./configure -q && sudo make -j3 install; )
    - name: init repository
      run: git submodule init; git submodule update
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure --enable-repobuild
    - name: make
      run: make -j10
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck

